[language-server]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "haskell"
scope = "source.haskell"
auto-format = true

[[language]]
name = "rust"
scope = "rust.toml"
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "toml"
scope = "source.toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true
