[language-server]

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
allFeatures = true

[[language]]
name = "haskell"
scope = "source.haskell"
auto-format = true

[[language]]
name = "rust"
scope = "source.rust"
formatter = { command = "rustfmt", args = ["--edition", "2024"] }

[[language]]
name = "toml"
scope = "source.toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "tsx"
scope = "source.tsx"
auto-format = true
